# Generated by Django 3.2.6 on 2021-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=30)),
                ('conform_password', models.CharField(max_length=30)),
            ],
        ),
    ]
