# Generated by Django 3.2.6 on 2021-10-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
